### ISSUE TITLE
how to train

### ISSUE THREAD

**Issue by ZXLAI** [difhnp/ELGLT#1]

**Comment by difhnp** [comment]
The training code and dataloader can be found in `modules/guider` and `modules/embedder`. You can modify the dataloader for your own data. To train the base tracker, please refer to [pysot](https://github.com/STVIR/pysot).

**Comment by ZXLAI** [comment]
Thanks

**Comment by yuuuuux** [comment]
@ZXLAI 你好，请问你训练成功了吗？我训练发现缺少数据集，可以方便请教一下怎么处理的吗
