### ISSUE TITLE
为什么运行了run_lasot.py生成的.txt文件当中出现大量负值，追踪结果是有误的

### ISSUE THREAD

**Issue by smilingChen** [difhnp/ELGLT#2]

**Comment by difhnp** [comment]
@smilingChen  你好，是所有结果都有问题吗？
我刚刚重新clone下来测试了一下，没发现问题。能否提供详细信息？

**Comment by smilingChen** [comment]
@difhnp 作者你好，我只测试了run_lasot.py,在运行之后生的txt文件出现负值，下面是lasot的airplane-1运行出的结果
[airplane-1.txt](https://github.com/difhnp/ELGLT/files/10877597/airplane-1.txt)

**Comment by difhnp** [comment]
@smilingChen 你这个结果与我跑出来的结果不一致，请检查一下环境配置是否正确、版本是否一致。另外，出现负值一般是目标丢失造成的，可以打开`self.show_flag`看下可视化结果。

**Comment by smilingChen** [comment]
@difhnp 作者你好，请问你的opencv是多少版本的？当修改VOT_FLAG为True的时候run_lasot.py中的import vot 
 handle = vot.VOT("polygon")的这个地方报NO module vot错误，是缺少一个vot.py文件的问题吗？

**Comment by difhnp** [comment]
`opencv-python=4.7.0.72`
是缺一个vot.py文件，要到vot-toolkit里找

**Comment by smilingChen** [comment]
@difhnp 好的，谢谢作者的答复

**Comment by smilingChen** [comment]
@difhnp 作者你好，我再次调整了环境，然后运行了run_lasot.py但是结果仍然与之前一样，请问在测试运行run_lasot.py之前还需要进行别的处理吗？

**Comment by smilingChen** [comment]
@difhnp 作者你好，请问数据集的格式是什么样的？

**Comment by difhnp** [comment]
LaSOT的原始数据，加上pysot的json文件
