### ISSUE TITLE
重检测模块

### ISSUE THREAD

**Issue by bazhahei0531** [difhnp/ELGLT#3]
请问重建测模块的训练数据集是什么样的格式呀?重建测模块训练部分train_guided2.py没调通.我已经给了数据集路径.但是env = lmdb.open(self.data_path[name], readonly=True, lock=False, readahead=False, meminit=False)  这句代码报找不到我的数据集路径的错误.   拜托方便的时候回一下哦,万分感谢!

**Comment by yasoooooo** [comment]
请问问题解决了吗？我也是这个问题

**Comment by bazhahei0531** [comment]
不好意思，没有解决哦











在 2024-03-25 02:22:32，"油炸皮卡丘" ***@***.***> 写道：

请问问题解决了吗？我也是这个问题
