### ISSUE TITLE
Problem in downloading the model.zip and skim.zip!!!

### ISSUE THREAD

**Issue by chenfsjz** [difhnp/ELGLT#4]
Hello! Thank you for sharing your project!
Because it is not convinient for me to download  model.zip and skim.zip in google drive, can you share the models on baidu cloud?
Thanks again for your excellent work!

**Comment by difhnp** [comment]
link: https://pan.baidu.com/s/19ccNKWz7_9qUetNmxKquGQ?pwd=2jsc 
passwd: 2jsc
